### ISSUE TITLE
pycryptodome is missing from setup.py

### ISSUE THREAD

**Issue by stanorama** [cesbit/aiowmi#14]
**Describe the bug**
pip install aiowmi does not install the dependency of pycryptodome.

**To Reproduce**
pip install aiowmi

**Expected behavior**
All package dependencies should be installed by pip

**Additional context**
Add install_requires to setup.py, or consider switching to the new standard pyproject.toml

Great package btw!

**Comment by joente** [comment]
Added to setup.py in version v0.1.18
