### ISSUE TITLE
WMIC Server Terminates with [FIN, ACK] on RemoteCreateInstance response

### ISSUE THREAD

**Issue by jayrajsingh** [cesbit/aiowmi#30]
**Describe the bug**
When trying to make a WMIC call using check_wmi_plus (v1.68) the call is failing continuously with the below copied error message.
"UNKNOWN - The WMI query had problems. We're not exactly sure what this error is. There was some kind of problem performing the WMI query on the target host (10.232.xx.xx). Wmic error text on the next line.

Problem with the wmi query on the target host. WBEM_E_UNKNOWN (2147944122)"

**To Reproduce**
1. Setup WMIC server on CentOS 7.6 and install Nagios with check_wmi_plus plug-in
2. Trigger a check_wmi_plus command to query Windows node system properties (eg. CPU/RAM)
3. Run  the  command "check_wmi_plus.pl -H 10.232.xx.xx -m checkmem -u UserName/Password -w 80 -c 90"

**Expected behavior**
Expected to see  a reponse with CPU/RAM utilization

**Screenshots**
Error Screen-1
<img width="1045" alt="image" src="https://github.com/cesbit/aiowmi/assets/7914830/d6e60cdf-2f56-4f67-b2ae-44e8e7b550bb">

Error Screen-2
<img width="993" alt="image" src="https://github.com/cesbit/aiowmi/assets/7914830/ddda7a4a-04e7-44d0-aada-bd9103e391ff">

N/W Trace  Screen-1 
![image](https://github.com/cesbit/aiowmi/assets/7914830/38e0d800-6f78-4c06-b6c7-8b6d0b0e70e8)

N/W  Trace Screen-2
![image](https://github.com/cesbit/aiowmi/assets/7914830/5387d138-0d97-4b6e-8b41-7a17ef4fc7dd)

**Comment by riklempens** [comment]
@jayrajsingh does this issue still occur?
If so can you verify firewall settings on the Windows host are correct?
See our InfraSonar documentation on how to configure these:
https://docs.infrasonar.com/collectors/probes/wmi/#firewall-requirements

**Comment by riklempens** [comment]
@jayrajsingh I am closing this issue, feel free to re-open if needed.
