### ISSUE TITLE
Windows 10 WBEM_E_ACCESS_DENIED

### ISSUE THREAD

**Issue by KoBOLL** [cesbit/aiowmi#35]
**Describe the bug**
Get ```WBEM_E_ACCESS_DENIED``` while trying to query ```SELECT Name FROM Win32_UserAccount``` on remote Windows 10 machine. Same code works as expected on Windows 7 and Windows Server 2019.

The user on the target machine is configured correctly because ```wbemtest``` from another Windows 10 is working correctly. However, ```wbemtest``` running from Windows 7 also gives access denied.

This appears in function __anext__ from qcontext.py

**To Reproduce**
Try to query from Win32_UserAccount

**Expected behavior**
Get user accounts

**Additional context**
It is worth noting that quering ```SELECT * FROM __InstanceCreationEvent``` works as expected.

**Comment by riklempens** [comment]
@KoBOLL please have a look at our [InfraSonar troubleshooting guide](https://docs.infrasonar.com/collectors/probes/wmi/wmi-troubleshooting/#access-denied) for WMI.

Let me know if this helped you fix the issue.

The issue is potentially not related to the aiowmi library but seems to be a local configuration issue on the Windows 10 system.

**Comment by KoBOLL** [comment]
> @KoBOLL please have a look at our [InfraSonar troubleshooting guide](https://docs.infrasonar.com/collectors/probes/wmi/wmi-troubleshooting/#access-denied) for WMI.
> 
> Let me know if this helped you fix the issue.
> 
> The issue is potentially not related to the aiowmi library but seems to be a local configuration issue on the Windows 10 system.

Thank you, sir.
After ```winrm quickconfig``` all works as expected.

But I'm still very curious - why ```wbemtest``` on windows 10 and ```impacket``` worked without this command. I'd really appreciate it if you could point me in the right direction.

**Comment by riklempens** [comment]
> But I'm still very curious - why wbemtest on windows 10 and impacket worked without this command. I'd really appreciate it if you could point me in the right direction.

Where both Windows 10 hosts active directory joined? Or perhaps using the same account name and password? wbemtest does not have to authenticate in this scenario as there is already a trusted connection.

I am unclear why impacket is working but maybe this was executed in a similar setup than how you performed the wbem test.

Would you be interested in having a look at our monitoring solution [InfraSonar](https://infrasonar.com), it is open source with a managed backend.
